
package com.example.client.soapClient;

import jakarta.xml.ws.*;

import javax.xml.namespace.QName;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogEntrySoapWebServiceImplService", targetNamespace = "http://logEntry.rest.example.com/", wsdlLocation = "http://localhost:8081/logEntry?wsdl")
public class LogEntrySoapWebServiceImplService
    extends Service
{

    private final static URL LOGENTRYSOAPWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGENTRYSOAPWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName LOGENTRYSOAPWEBSERVICEIMPLSERVICE_QNAME = new QName("http://logEntry.rest.example.com/", "LogEntrySoapWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/logEntry?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGENTRYSOAPWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LOGENTRYSOAPWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LogEntrySoapWebServiceImplService() {
        super(__getWsdlLocation(), LOGENTRYSOAPWEBSERVICEIMPLSERVICE_QNAME);
    }

    public LogEntrySoapWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGENTRYSOAPWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public LogEntrySoapWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LOGENTRYSOAPWEBSERVICEIMPLSERVICE_QNAME);
    }

    public LogEntrySoapWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGENTRYSOAPWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public LogEntrySoapWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogEntrySoapWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogEntrySoapWebServiceImpl
     */
    @WebEndpoint(name = "LogEntrySoapWebServiceImplPort")
    public LogEntrySoapWebServiceImpl getLogEntrySoapWebServiceImplPort() {
        return super.getPort(new QName("http://logEntry.rest.example.com/", "LogEntrySoapWebServiceImplPort"), LogEntrySoapWebServiceImpl.class);
    }


    @WebEndpoint(name = "LogEntrySoapWebServiceImplPort")
    public LogEntrySoapWebServiceImpl getLogEntrySoapWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://logEntry.rest.example.com/", "LogEntrySoapWebServiceImplPort"), LogEntrySoapWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGENTRYSOAPWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LOGENTRYSOAPWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return LOGENTRYSOAPWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
